#!/usr/bin/env bash

set -eu

overwrite_all=false

for file in ~/.dot/files/*; do
  overwrite=false

  basename=${file##*/}
  target="$HOME/.$basename"

  if [ -e "$target" ]; then
    if ! $overwrite_all; then
      while true; do
        echo "$target already exists"
        printf "[s]kip, [S]kip all, [o]verwrite, [O]verwrite all: "
        read answer
        case $answer in
          "s") continue 2;;
          "S") break 2;;
          "o") overwrite=true; break;;
          "O") overwrite_all=true; break;;
           * ) continue;;
        esac
      done
    fi

    if $overwrite || $overwrite_all; then
      rm $target
    fi
  fi

  echo "* linking $target => $file"
  ln -s "$file" "$target"
done

bindir=~/.dot/bin

if ! echo $PATH | grep -q $bindir; then
  echo -e "\nRemember to add $bindir to path."
fi
