#!/usr/bin/env bash

set -eu

# Prezto

if [ ! -d ~/.zprezto ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto
fi

# Powerline

for pkg in {powerline-status,psutil,netifaces}; do
  [ ! "$(pip list | grep $pkg)" ] && pip install $pkg
done

if [ ! -e ~/.config/powerline ]; then
  mkdir -p ~/.config
  ln -ns ~/.dot/etc/powerline ~/.config/powerline
fi

# Dotfiles

echo "Linking dotfiles..."

overwrite_all=false

for file in ~/.dot/files/*; do
  overwrite=false

  basename=${file##*/}
  target="$HOME/.$basename"

  if [ -e "$target" ]; then
    if ! $overwrite_all; then
      while true; do
        echo "$target already exists"
        printf "[s]kip, [S]kip all, [o]verwrite, [O]verwrite all: "
        read answer
        case $answer in
          "s") continue 2;;
          "S") break 2;;
          "o") overwrite=true; break;;
          "O") overwrite_all=true; break;;
           * ) continue;;
        esac
      done
    fi

    if $overwrite || $overwrite_all; then
      rm $target
    fi
  fi

  ln -sv "$file" "$target"
done
