#!/usr/bin/env bash

set -eu

dotdir=~/.dot
bindir=$dotdir/bin

cd $dotdir

dotfiles=$(find files -name "dot.*")

overwrite_all=false

for file in $dotfiles; do
  overwrite=false

  basename=${file##*dot}
  target="$HOME/$basename"

  if [ -e "$target" ]; then
    if ! $overwrite_all; then
      while true; do
        echo "$target already exists"
        printf "[s]kip, [S]kip all, [o]verwrite, [O]verwrite all: "
        read answer
        case $answer in
          "s") continue 2;;
          "S") break 2;;
          "o") overwrite=true; break;;
          "O") overwrite_all=true; break;;
           * ) continue;;
        esac
      done
    fi

    if $overwrite || $overwrite_all; then
      rm $target
    fi
  fi

  echo "* linking $target => $PWD/$file"
  ln -s "$PWD/$file" "$target"
done

if ! echo $PATH | grep -q $bindir; then
  echo -e "\nRemember to add $bindir to path."
fi
