#!/usr/bin/env bash

set -eu

cd ~/.dot

dotfiles=$(find files -name "dot.*")

for file in $dotfiles; do
  basename=${file##*dot}
  target="$HOME/$basename"

  if [ -h "$target" ]; then
    echo "* unlinking $target"
    rm $target
  fi
done
