#!/bin/sh

set -eu

# Hardcode path to keep Cthulhu away
cd ~/.dot

dotfiles=$(find files -name "*.dot")

for file in $dotfiles; do
  basename=.$(basename $file .dot)
  target="$HOME/$basename"

  if [ -h "$target" ]; then
    echo "* unlinking $target"
    rm $target
  fi
done
