#!/usr/bin/env ruby

# My playground setup
begin
  require "duplo"
  include Duplo
rescue LoadError
end

# Display project/folder name in prompt
Pry.config.prompt_name = File.basename(Dir.pwd)

# Display Rails/Rack env in prompt
if env = ENV["RAILS_ENV"] || ENV["RACK_ENV"]
  env = Pry::Helpers::Text.red(env)
  prompt = Pry::Prompt[:default]

  Pry.config.prompt = Pry::Prompt.new(
    'Rack',
    'Rack prompt',
    [
      proc { |*a| "#{env} #{prompt.wait_proc.call(*a)}" },
      proc { |*a| "#{env} #{prompt.incomplete_proc.call(*a)}" }
    ]
  )
end

Pry.config.correct_indent = false if ENV["EMACS"]
