#!/usr/bin/env ruby

# My playground setup
begin
  require "duplo"
  include Duplo
rescue LoadError
end

# Display project/folder name in prompt
Pry.config.prompt_name = File.basename(Dir.pwd)

# Display env in prompt if applicable
if env = ENV["RAILS_ENV"] || ENV["RACK_ENV"] || ENV["ENVIRONMENT"]
  env = Pry::Helpers::Text.red(env)
  prompt = Pry.config.prompt
  Pry.config.prompt = [
    proc { |*a| "[#{env}] #{prompt[0].call(*a)}" },
    proc { |*a| "[#{env}] #{prompt[1].call(*a)}" }
  ]
end

Pry::Commands.alias_command "reload", "reload-method"

if ENV["EMACS"]
  Pry.config.correct_indent = false
end
