# Sourced in interactive shells.

# Common shell config
[ -f ~/.shellrc ] && source ~/.shellrc

export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000

setopt APPEND_HISTORY         # Append to history file
setopt AUTO_CD                # If command cannot be executed, try to cd
setopt EXTENDED_HISTORY       # Record the time of each command
setopt HIST_EXPIRE_DUPS_FIRST # Expire a duplicate event first when trimming history
setopt HIST_FIND_NO_DUPS      # Do not display a previously found event
setopt HIST_IGNORE_ALL_DUPS   # Delete an old recorded event if a new event is a duplicate
setopt HIST_IGNORE_DUPS       # Do not record an event that was just recorded again
setopt HIST_IGNORE_SPACE      # Do not record an event starting with a space
setopt HIST_NO_STORE          # Don't store history commands
setopt HIST_SAVE_NO_DUPS      # Do not write a duplicate event to the history file
setopt HIST_VERIFY            # Do not execute immediately upon history expansion
setopt INC_APPEND_HISTORY     # Write to the history file immediately, not when the shell exits
setopt PROMPT_SUBST           # Allow expansion in prompt string
setopt SHARE_HISTORY          # Share history between all sessions

# Disable autocorrect guesses
unsetopt CORRECT

# Eliminate duplicate path entries
typeset -U PATH
typeset -U FPATH

# Initialize completion
autoload -Uz compinit && compinit

# Use generic completions for some utilities
compdef _gnu_generic rustc sidekiq byk

# brew completions
if type brew &>/dev/null; then
  fpath=($(brew --prefix)/share/zsh/site-functions $fpath)
fi

# fzf
fzf_paths=(~/.fzf.zsh /usr/share/doc/fzf/examples/completion.zsh /usr/share/doc/fzf/examples/key-bindings.zsh)

for fzf_path in ${fzf_paths[@]}; do
  [ -f "$fzf_path" ] && source "$fzf_path"
done

# Emulate bash binding for ^u
bindkey \^u backward-kill-line

# fzf hijacks alt+c, rebind original
bindkey "^[c" capitalize-word

# fzf, see https://github.com/ardnew/fzf/blob/master/ADVANCED.md
export FZF_DEFAULT_OPTS="--layout=reverse --info=inline"

# Tighten word boundaries
export WORDCHARS=''

# Minimalist prompt
git_prompt() {
  BRANCH=$(git branch --show-current 2> /dev/null)

  if [[ -n $BRANCH ]]; then
    if [ -z "$(git status --porcelain)" ]; then
      DIRTY="%F{green}✔"
    else
      DIRTY="%F{red}✗"
    fi

    echo -n " %F{green}($BRANCH $DIRTY%F{green})"
  fi
}

PS1='%~$(git_prompt)%F{reset} » '

# Echo failed exit status on the right
RPROMPT='%(?,,%F{red}$?)%f'
